### ISSUE TITLE
Macros aren't resolved in Cursive if they are required by the cljs namespace

### ISSUE THREAD

**Issue by maridonkers** [cursive-ide/cursive#1068]
In file: <https://github.com/bevuta/pepa/blob/master/src-cljs/pepa/components/root.cljs> (which is part of GIT project: <https://github.com/bevuta/pepa> GIT clone URL is: <https://github.com/bevuta/pepa.git>). The IntelliJ project was created from the project.clj file.

In the source code the line:

```clojure
(ui/defcomponent root-component [state owner]
```

is incorrectly marked with a  **ui/defcomponent cannot be resolved**. And the ns require 

```clojure
[nom.ui :as ui]
```

is incorrectly marked as **unused alias**

The macro is declared, albeit via a *require-macros* in between step (see code excerpt below, where the *(:require-macros nom.ui)* leads to the code where the *defcomponent* macro is defined. 

```clojure
(ns nom.ui
  (:require
   ;; Necessary for the `defcomponent' macro
   om.core
   sablono.core)
  (:require-macros nom.ui))
```

There are lots more (**cannot be resolved**, **unused alias** messages) shown in various files of the pepa project.

1.8.0_60-b27x64 Oracle Corporation, Linux(amd64) v3.16.0-4-amd64 unknown (1920x1080, 1366x768)

**Comment by maridonkers** [comment]
Later I found this comment: <https://github.com/cursiveclojure/cursive/issues/881#issuecomment-100560643> which possibly concerns the same problem (and reads it is fixed in next version by added type inference functionality in Cursive).

**Comment by maridonkers** [comment]
<https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure>

Macros are written in Clojure. (See the Lisp differences section above).

Unlike in Clojure, in ClojureScript a macro and a function can have the same name (for example the cljs.core/+ macro and cljs.core/+ function can coexist).

Note: You may be wondering: “If that's the case, which one do I get?” ClojureScript (unlike Clojure) has two distinct stages that make use of two separate non-interacting namespaces. Macroexpansion occurs first, so a form like (+ 1 1) initially involves the cljs.core/+ macro. On the other hand, in a form like (reduce + [1 1]), the + symbol is not in operator position, and passes untouched through macroexpansion to analysis/compilation where it is resolved as a the cljs.core/+ function.

**Comment by danielcompton** [comment]
In ClojureScript, if the cljs namespace does `:require-macros` on the clj namespace, then consumers of that namespace don't need to use `:include-macros` themselves. cljs.test is a good example of this.

run-tests is not resolved in the following code block

```
 [cljs.test :as cljs-test]
...

(cljs-test/run-tests
```

though it is if you change to 

```
 [cljs.test :as cljs-test :include-macros true]
```

**Comment by cursive-ide** [comment]
Right, I think this is the problem described in #775.

**Comment by cursive-ide** [comment]
This was fixed in 1.3.0.
