### ISSUE TITLE
Running a lein repl command with trampoline closes ide

### ISSUE THREAD

**Issue by favila** [cursive-ide/cursive#1356]
If you execute a lein repl command with the "use trampoline" box checked, IntelliJ will exit.

IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_77-b03 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by cprice404** [comment]
Are you using lein-cljsbuild?  You might be affected by this bug:

https://github.com/emezeske/lein-cljsbuild/issues/204

Which was fixed in a recent release of cljsbuild.

**Comment by cursive-ide** [comment]
What I suspect this means is that figwheel (or some other lein plugin that it interacts with) is calling `(System/exit)` upon some error condition. I'll try to reproduce this with a figwheel project.

**Comment by cprice404** [comment]
lein-cljsbuild was doing exactly that - that's what that bug report I linked above was about.  It's fixed in the latest version, though possible that there is some other library still doing that.

**Comment by cursive-ide** [comment]
@cprice404 My apologies, I had forgotten that that issue was an exiting one. @favila does that look like the bug you're seeing? Does upgrading cljsbuild fix it?

**Comment by zhanghuabin** [comment]
@cursive-ide  I tried 2016.1.2 + cursive 1.2.7 + lein-figwheel 0.5.3.-1 + lein-cljsbuild 1.1.3, this problem can be reproduced.

**Comment by souenzzo** [comment]
idea 2017.1.1, cursive 1.5.0-eap7-2017.1, clojure 1.8, lein 2.7.1, java 1.8.... Still occurs
