### ISSUE TITLE
Breakpoint hit on the wrong file

### ISSUE THREAD

**Issue by jhalterman** [cursive-ide/cursive#168]
I'm running the REPL in debug mode in a project with a `core.clj` file. I set a breakpoint on some line that also happens to exist in the `clojure/core.clj` file. When loading my local `core.clj` the breakpoint was hit, except instead of being on my local `core.clj` file it was hit on `clojure/core.clj`. Cursive/IntelliJ seems to be confusing the two files based on their having the same name.

There may be a few ways to reproduce this, but I happened to notice it when starting a REPL in debug mode with a compile error in my `core.clj`. I fixed the compile error and re-loaded the file, which triggered the breakpoint I had set on line 94 in my local `core.clj`. Execution stopped on line 94 in `clojure/core.clj` which happens to be the `second` function (in 1.5.1).

Interestingly, I noticed the [same/similar issue](https://code.google.com/p/counterclockwise/issues/detail?id=606) recently in CCW.

**Comment by cursiveclojure** [comment]
I could never reproduce this reliably, but I've just fixed a lot of bugs in this piece of code for the next build - I'm hopeful this is resolved now. Please let me know if this is not the case.

**Comment by grammati** [comment]
I can now reproduce this reliably.

I start my REPL from emacs/cider, then connect the Intellij debugger (see #1195). Then I set a breakpoint at line 17 in a namespace called, `pigeon.utils`. Upon typing in emacs, Intellij repeatedly breaks in the function `compliment.utils/fuzzy-matches?`. Compliment is the completion backend for cider.

I'm guessing that this is related to the fact that compliment has been inlined into cider-nrepl using mranderson, and so Intellij does not know where to find its source.

![screen shot 2015-12-20 at 5 45 19 am](https://cloud.githubusercontent.com/assets/94716/11918027/53c5581e-a6dd-11e5-82d8-29c4c296a438.png)

**Comment by cursive-ide** [comment]
@grammati I'm very interested in repro steps for this. Is Pigeon an open project?

**Comment by grammati** [comment]
No, sorry, it's not. But I suspect that any project with a "utils"
namespace will work.

**Comment by cursive-ide** [comment]
Unfortunately it's not - Cursive has one and I can only reproduce it sporadically, and never when I want to. But I'll try again now that I know it's still an issue.

**Comment by Bill** [comment]
I see the problem in this public repo: https://github.com/Bill/iiqm-clj

I set a breakpoint on line 83 of `/src/iiqm/core.clj` and then I fire up a local debug REPL and load that `core.clj` file into the REPL and then I eval this expr: `(conj iiqm3 1)`. That (wrongly) breaks on line 83 of the Gorilla REPL file `/plots.clj`.

Note that a) that Gorilla REPL file is not required (either directly or indirectly) by my `core.clj` and b) that Gorilla REPL does define the same namespace: `iiqm.core`

**Comment by cursive-ide** [comment]
@Bill excellent, thanks - I'll try to reproduce with this.

**Comment by cursive-ide** [comment]
I've fixed @Bill's problem, although I couldn't actually reproduce it I could see what the problem was (it depended on the order in which the index subsystem returns results). But it's actually a different problem to @grammati's. I'll try to reproduce that one using Cider and a `utils` namespace.

**Comment by Bill** [comment]
Great @cursive-ide! Is there a way I can confirm the fix for you?

**Comment by cursive-ide** [comment]
@Bill I'm mostly on holiday for a bit now, if I find time I'll do a dev build for you to try, otherwise it'll be in the next EAP build.

**Comment by Bill** [comment]
No rush at all!

**Comment by cursive-ide** [comment]
@grammati So I think I've set up Emacs correctly, but I can't reproduce what you're seeing. How do you have compliment set up? It took a fair amount of cursing to get CIDER working, but right now I'm still completing with `M-tab`, and that may not invoke the fuzzy matching. How do you have it set up so that it completes on typing?

**Comment by grammati** [comment]
I just spent some time trying to reproduce this, as described here and in #1195, and I no longer can. Everything is working perfectly!

I don't know what changed to make this work, but I'm on Intellij 15 now, and I'm on snapshot versions of cider/cider-nrepl and clj-refactor/refactor-nrepl, so they can change at any time.

In case you still need to reproduce this, my emacs setup is here:

https://github.com/RallySoftware/rally-emacs

with the relevant files probably being these:

https://github.com/RallySoftware/rally-emacs/blob/master/rally/company.el
https://github.com/RallySoftware/rally-emacs/blob/master/profiles.clj

**Comment by cursive-ide** [comment]
@grammati: Bummer. If you can reproduce it again, let me know - I'm creating a diagnostic tool right now that will let me investigate this sort of thing.
