### ISSUE TITLE
Test dir not properly detected in IDEA 2018.1

### ISSUE THREAD

**Issue by katox** [cursive-ide/cursive#1963]
Unlike previous versions the `test` directory containing tests is not properly recognized by Leiningen integration. It works as expected with the previous version. 

Note: IDEA complained about Kotlin library incompatiblity.

Attached views of Project vs Project Files.
![tests-not-present-in-project](https://user-images.githubusercontent.com/287639/37769926-03f939de-2dd3-11e8-8251-bec93192c460.png) - the directory can't be expanded

![test-dir-in-project-files](https://user-images.githubusercontent.com/287639/37769935-067c068c-2dd3-11e8-9dfb-960988cc9087.png) - normal contents (including color coding of test source dir).

The project.clj contains

    :source-paths ["src/clj"]
    :java-source-paths ["src/java"]
    :resource-paths ["resources"]
    :profiles
      {:dev           [:project/dev :profiles/dev]
       :project/dev  {:dependencies [[prone "1.5.0"]
                                 [ring/ring-mock "0.3.2"]
                                 [ring/ring-devel "1.6.3" 
                                          :exclusions [org.clojure/java.classpath]]
                                 [org.clojure/test.check "0.9.0"]]
                  :plugins      [[com.jakemccrary/lein-test-refresh "0.14.0"]]

                  :source-paths ["env/dev/clj" "test/clj"]
                  :resource-paths ["env/dev/resources"]
                  :repl-options {:init-ns user}
                  }
        :project/test {:resource-paths ["env/dev/resources" "env/test/resources"]}
        :profiles/dev {}
        :profiles/test {}})

**Comment by cursive-ide** [comment]
I can't reproduce this, but I have seen some funkiness with the project directories on 2018.1. In this case, I wonder whether it's because you have a source folder (blue) nested inside a test source folder (green), which is unusual. I fixed this by doing the following:

```
  :source-paths ["src/clj"]
  :test-paths []
  :java-source-paths ["src/java"]
  :resource-paths ["resources"]
  :profiles
  {:dev           [:project/dev :profiles/dev]
   :project/dev  {:dependencies [[prone "1.5.0"]
                                 [ring/ring-mock "0.3.2"]
                                 [ring/ring-devel "1.6.3"
                                      :exclusions [org.clojure/java.classpath]]
                                 [org.clojure/test.check "0.9.0"]]
                  :plugins      [[com.jakemccrary/lein-test-refresh "0.14.0"]]

                  :source-paths ["env/dev/clj"]
                  :test-paths ["test/clj"]
                  :resource-paths ["env/dev/resources"]
                  :repl-options {:init-ns user}}

   :project/test {:resource-paths ["env/dev/resources" "env/test/resources"]}
   :profiles/dev {}
   :profiles/test {}})
```

Note the use of `:source-paths` and `:test-paths` at both the root level and inside `:project/dev`. This creates the following for me:

![screen shot 2018-03-23 at 16 25 18](https://user-images.githubusercontent.com/5589171/37810003-de8efac2-2e49-11e8-9bd8-48299ced9eb4.png)

Does that help in your real project?

**Comment by katox** [comment]
I tried the suggested change and the test/clj dir turned green. So both test and clj icons are "test" sources now. Other than that no change unfortunately.
I also updated the idea from RC to 2018.1 final but no luck either. I removed the old .idea and *.iml files and tried to import from scratch but the result is the same :/. There is no error in the idea system log.
Both modified and unmodified project.clj work in version 2017.

**Comment by cursive-ide** [comment]
> I tried the suggested change and the test/clj dir turned green. So both test and clj icons are "test" sources now.

@katox Sorry, re-reading this I realise that I missed something - in your actual project, both the `test` dir and the `clj` dir it contains are marked in green? That is not what you want, and might be causing your problems. Do you also have the `:test-paths []` line at the top level in your project file?

**Comment by cursive-ide** [comment]
@clartaq Thanks for the repro case, I managed to use that to see the problem. It definitely looks like IntelliJ 2018.1 has a problem with source paths nested inside each other. In this case (the reagent project) the `project.clj` has: 
```
  :cljsbuild
  {:builds {...
            :test
            {:source-paths ["src/cljs" "src/cljc" "test/cljs"]
            ...
```
So Cursive will create source directories at each of those points. However by default lein adds `test` to the list of `:test-sources`, so Cursive marks `test` as a test folder, and `test/cljs` as a source folder, which causes this funkiness. If you add `:test-paths []` at the top level so lein doesn't add `test` as a test source folder, things look ok.

The problem with adding `:test-paths ["test/cljs"]` as you suggest is that that directory will be on the classpath for every task you run using lein, including things like Clojure compilation. Since presumably it only contains cljs code you might not see problems, but it's probably better to configure it properly.

**Comment by katox** [comment]
@cursive-ide I totally overlooked the `:test-paths []` change at the top level. It seems to fix the problem!
Without it both `test` and `test/clj dirs` were marked green and the problem persisted.

I didn't know that lein added `test` dir to test-paths by default because test source files weren't detected at all without an extra directive in `:dev` - probably because the hierarchy didn't reflect test namespaces (the extra `clj` "package").

I'll try to test it a bit more in 181.4445.20. The official 2018.1 was buggy as hell so I had to roll it back to 2017 away.

**Comment by clartaq** [comment]
Great! I didn't know that about lein and the `test` dir.

**Comment by cursive-ide** [comment]
This is tracked in [IDEA-190196](https://youtrack.jetbrains.com/issue/IDEA-190196). I'm going to leave this open for the moment and think about whether I should trim nested source roots to prevent this sort of thing.
